### ISSUE TITLE
README should have information on usage

### ISSUE THREAD

**Issue by shymega** [manageplaces/Stompex#1]
For new users, the README should have information on how to use it.

Perhaps that could be added in to encourage new users?

**Comment by pareeohnos** [comment]
Agreed, this is very much needed, it's just been put onto the back burner as this was written to go into a larger application we're working on, but I will get basic documentation added to it :)

Sorry for the delay, didn't see a notification of the issue

**Comment by pareeohnos** [comment]
Have updated the readme. It should now be much easier for someone to get started :)

**Comment by shymega** [comment]
It looks it! Thanks so much for this.
