### ISSUE TITLE
Crash when using schedules delay as properties

### ISSUE THREAD

**Issue by jankomartin** [manageplaces/Stompex#6]
Hello, 
I tried to use the stompex library. In basic setup everything looks ok. But when I tried to receive message which has property "AMQ_SCHEDULED_DELAY" the receiver die. This property can be set from ActiveMQ admin webconsole (function "Send to").

```
%Stompex.Frame{body: nil, cmd: "MESSAGE", content_type: nil, headers: %{}}
** (EXIT from #PID<0.156.0>) an exception was raised:
    ** (MatchError) no match of right hand side value: nil
        (stompex) lib/stompex/receiver/receiver.ex:62: Stompex.Receiver.process_header/2
        (stompex) lib/stompex/receiver/receiver.ex:57: Stompex.Receiver.read_headers/3
        (stompex) lib/stompex/receiver/receiver.ex:34: Stompex.Receiver.do_receive/1
        (stompex) lib/stompex/receiver/receiver.ex:13: Stompex.Receiver.handle_cast/2
        (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
        (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

```

I'm using following code to retrieve the messages. 
```
{ :ok, conn } = Stompex.connect("localhost", 61613,"admin","admin")

callback = fn (msg) ->
  IO.puts msg
end

Stompex.register_callback conn, "/queue/xxx", callback
Stompex.subscribe conn, "/queue/xxx"
```

Please can you advice

**Comment by pareeohnos** [comment]
Hey,

Do you have the raw frame that is being sent when it fails? The error would suggest that it's failing to parse one of the headers, so I'm wondering if it's being sent incorrectly. The frame should look like

    MESSAGE

    AMQ_SCHEDULED_DELAY: value
    ....

I'm wondering if the `: value` part is missing?

**Comment by jankomartin** [comment]
Unfortunately I do not have the raw frame. But when I'm checking the message over the web console. The property is on line "AMQ_SCHEDULED_DELAY: 10".
I have tried to modified the your library code so it dumps the incoming data, but without luck. I'm just newbie in elixir.

**Comment by pareeohnos** [comment]
Not to worry, just found the issue. It appears that the regex which checks for header lines was ignoring underscore characters, and was therefore not matching that header. I've just pushed the fix onto master so give that a go :)

**Comment by jankomartin** [comment]
I remove the deps folder and after mix get.deps there is still the "same" crash. Should I wait to be it somehow propagated to mix / git ? I can see you commit on the web but not when I update mine project.

**Comment by pareeohnos** [comment]
try running `mix deps.update stompex` or just `mix deps.update`. Removing the `deps` folder will wipe out all of the code, but your `mix.lock` file will still be referencing the same version as before, so you'll need to force it to fetch a new version.

**Comment by jankomartin** [comment]
Work perfectly. 

THX for help.

**Comment by pareeohnos** [comment]
Excellent :) no problem, thanks for raising the issue. Let me know if you run into any other problems. Enjoy elixir :D
